### ISSUE TITLE
What images are in scope for this project and the jupyterhub org?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyter-remote-desktop-proxy#55]
This is a response to #51 extracted to a dedicated issue to have a more focused discussion without cluttering the PR.

---

I think having a minimal image as part of this project is great because it represents the functionality tied to jupyterhub that this project introduces, and being based on a jupyter/docker-stacks image we are able to focus on the specific things relevant to this project. I see it as a surgical addition that:
- could enable end-to-end testing (installation steps etc.)
- could provide a simple project demo
- could drive project adoption

Anything beyond that is something I'm still reflecting on, which makes me very greatful to see an explicit policy about this right away @yuvipanda!!

From the [policy section](https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/51/commits/880077ab87ef5ec1d1984e28233cae4c9205734f#diff-2ca137f168c2867f538f7904b891a4274d087ec5812412b56d8089871718b14cR32-R41):

> ## Policy for adding images
>
>To reduce maintenance burden, we will only accept maintaining images here that
match the following criteria:
>
>1. They add an application with a _popular_ scientific use case.
>2. The application is already package and maintained in `conda-forge`.
>
>Users are encouraged to build and maintain their own images where possible,
inheriting from the base image here for ease of use.

With a jupyterhub hat on, I'd like to think a bit extra before committing to maintaining anything beyond the minimal image.

## Alternative policy ideas

I've brainstormed a few policy ideas below to help us discuss what we think makes sense.

### 1) a minimal image + a flora of images

Going beyond providing just a minimal desktop image _maintaing a flora of images_ has a significant risk of being too taxing for the jupyterhub team. Most flora projects stop flourishing because unsustainable growth (helm/helm-charts, jupyterhub/oauthenticator, kubernetes in-tree software for third party components, maybe terraform also?).

I think this project receives the best value per maintenance by maintaining only one minimal image, or possibly one minimal and one advanced example. With that in mind I think we shouldn't consider maintaing a flora of images.

### 2) a minimal image + an advanced image example

I think having a single advanced image example alongside the minimal desktop image could help this project become aware of and resolve likely challenges in real world situations. I think the coupling to some specific well used software like QGIS could be acceptable as it becomes a real world use case that helps us test and validate the project.

I've written this as "an example" as I don't think it would be in scope for this project to ensure it would be an image that works out well for direct use given various periphiary needs users may have. I also think its reasonable that we don't need to maintain a changelog if we introduce a breaking change to the advanced example image, but I think we should for the minimal image if we have an advanced image example in this repo.

### 3) a minimal image + "explanation" documentation + links

I see this as a slim version of 2), where a advanced image example isn't provided in the repo, but documentation in the "explanation" category (https://diataxis.fr) to help create an advanced image is. Such explanation docs could include info about MIME types etc.

Beyond such explanation based docs (which is easier to maintain tha how-to docs), it would make perfect sense to link out to known externally maintained advanced images for practical examples.

### 4) just a minimal image + links

Even slimmer than 3), where we don't commit to maintaining explanation based docs, but just link out to other projects.

### 5) no images

To not introduce any image and to clear away the Dockerfile we have.

**Comment by consideRatio** [comment]
I'm leaning towards option 3 or option 4 long term, but I'm thinking short term the best call is to go for option 2 short term with an explicit intent to go for option 3 or 4 (by extracting the QGIS image to be maintained outside the jupyterhub org).

**Disclaimer: my goals with this discussion**

- To make the jupyterhub team comfortable with the path forward
- To minimize this discussions disruption of Yuvi's productivity to get things done

**Comment by yuvipanda** [comment]
## On the importance of flora of images

> 1) a minimal image + a flora of images
>
> Going beyond providing just a minimal desktop image maintaing a flora of images has a significant risk of being too taxing for the jupyterhub team. Most flora projects stop flourishing because unsustainable growth (helm/helm-charts, jupyterhub/oauthenticator, kubernetes in-tree software for third party components, maybe terraform also?).
>
> I think this project receives the best value per maintenance by maintaining only one minimal image, or possibly one minimal and one advanced example. With that in mind I think we shouldn't consider maintaing a flora of images.

Talking about [the helm/charts](https://github.com/helm/charts) repo is actually very instructive! 
I was around during the start of it, so I have some historical context that may help see it for
the absolutely massive success it is.

Helm is *currently* the defacto way to manage and install apps on k8s. However, this was
not some 'inevitable' conclusion. [ksonnet](https://github.com/ksonnet/ksonnet) was heavily favored inside the kubernetes
team itself - it was [pushed by heptio, microsoft, box and bitnami](https://blog.bitnami.com/2017/05/ksonnet-open-source.html)
including one of the primary creators of Kubernetes (Joe Beda). Kubernetes was a descendent of the
[Borg system](https://research.google.com/pubs/archive/44843.pdf) inside Google, and ksonnet was the equivalent
of Google Configuration Language (GCL) used internally for configuring Borg. Helm was also text templating,
while ksonnet used Jsonnet, which was more of a 'real' programming
language. At that time, helm also required a daemon (tiller) with elevated privileges that
ksonnet did not. So there was a strong possibility that ksonnet would
'win'.

Of course, many years later, ksonnet is completely dead and helm won. I think the *biggest* factor for helm winning was
the existence of the `helm/charts` repository. With that, *end users* of helm could actually get going immediately,
and new charts grew quickly as well. With ksonnet, you had to either write your own, even if it was for something
that was very commonly used (like prometheus), or hunt around for randomly half-maintained things you could use.
The `helm/charts` repo succeeded catastrohpically, and eventually got so big it dissolved into a lot of tiny
separate repos, maintained by the communities individually. This was ok at this stage of helm's life - it was
mature, and this splintering worked out ok. 

For me, the primary learning from this is that it is important to recognize that projects have a life cycle,
and different decisions are appropriate at different points in that cycle. When `helm` was started,
**it needed users to survive**. And `helm/charts` was important in bringing it users.

However, this is not to say we should sacrifice maintainers at the alter of 'we need more users!'.
Quite the contrary. In classical open source fashion, a small % of users become contributors, and the
project grows. Without a combination of:

1. A large number of users,
2. *Some* of whom grow into contributors

projects will never outgrow the initial list of maintainers, who all
will burn out. This may be slowed down by narrowing the scope of the
project, but ultimately it just extends the lifetime and is not a
sustainable solution.

This project - `jupyter-remote-desktop-proxy` currently is in a phase
where for it to succeed, it needs users. In the same way that users of
helm cared about it to install specific, common applications they
needed, users of `jupyter-remote-desktop-proxy` primarily care about
*applications* they want to use. Setting some of these up, especially
inside Docker containers, can be tricky - and heavily benefits from
being centralized *at this point of time*. This may change once it
gets bigger, and that's ok!

This was also true for in-tree volume drivers and cloud providers in kubernetes -
it was very instrumental in helping kubernetes succeed against Mesos and 
Docker swarm. Moving them out to CSI drivers *eventually* was the right call,
but so was including them in-tree in the beginning.

## Right place for the flora

With that said, I agree that this repo is not the right place for this 'flora of images'. Everything I said above applies to the broad Jupyter ecosystem of images, and not just to desktop software. Just 'desktop software' is too narrow a definition for such a flora to succeed, as I think it may not attract enough end users to sustain itself nor bring in new folks into *contributing* to jupyter-remote-desktop-proxy. I have a lot of thoughts and ideas on how to build a successful 'flora of images' project, based on things I have learnt from many other projects that have done this before. However, this repo is probably not the place for that, so I'm going to close that PR and bring my ideas to life somewhere else (especially since https://github.com/jupyter/docker-stacks/pull/1961 was also basically rejected, which is what led to me making the PR here anyway 😢). I'll provide a link here once I have something up and running.
